package breeze.rule;

macro function blur(...exprs);
macro function brightness(...exprs);
macro function contrast(...exprs);
macro function dropShadow(...exprs);
macro function grayscale(...exprs);
macro function hueRotate(...exprs);
macro function invert(...exprs);
macro function saturate(...exprs);
macro function sepia(...exprs);
macro function backdropBlur(...exprs);
macro function backdropBrightness(...exprs);
macro function backdropContrast(...exprs);
macro function backdropGrayscale(...exprs);
macro function backdropHueRotate(...exprs);
macro function backdropInvert(...exprs);
macro function backdropOpacity(...exprs);
macro function backdropSaturate(...exprs);
macro function backdropSepia(...exprs);
